'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Namespace XpoTutorial2.DataModel

    Partial Public Class Customer
        Inherits XPObject

        Private fName As String
        Public Property Name() As String
            Get
                Return fName
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Name", fName, value)
            End Set
        End Property
        Private fAge As UShort
        Public Property Age() As UShort
            Get
                Return fAge
            End Get
            Set(ByVal value As UShort)
                SetPropertyValue(Of UShort)("Age", fAge, value)
            End Set
        End Property
        <Association("OrderReferencesCustomer", GetType(Order))> _
        Public ReadOnly Property Orders() As XPCollection(Of Order)
            Get
                Return GetCollection(Of Order)("Orders")
            End Get
        End Property
    End Class

End Namespace
