'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Namespace XpoTutorial2.DataModel

    Partial Public Class Order
        Inherits XPObject

        Private fProductName As String
        Public Property ProductName() As String
            Get
                Return fProductName
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("ProductName", fProductName, value)
            End Set
        End Property
        Private fOrderDate As Date
        Public Property OrderDate() As Date
            Get
                Return fOrderDate
            End Get
            Set(ByVal value As Date)
                SetPropertyValue(Of Date)("OrderDate", fOrderDate, value)
            End Set
        End Property
        Private fCustomer As Customer
        <Association("OrderReferencesCustomer")> _
        Public Property Customer() As Customer
            Get
                Return fCustomer
            End Get
            Set(ByVal value As Customer)
                SetPropertyValue(Of Customer)("Customer", fCustomer, value)
            End Set
        End Property
    End Class

End Namespace
